### ISSUE TITLE
Calibration code

### ISSUE THREAD

**Issue by jamie-nxtgencare** [vassdoki/opencv-darts#1]
"The calibration code is not included, send me the calib_points.csv and I will send you the calibration. This will be an online service later. My username is the same on gmail."

Seriously?

**Comment by vassdoki** [comment]
Why don't you like the idea?

**Comment by jamie-nxtgencare** [comment]
I have no problem with you providing a calibration service, I think it's pretty cool. And so far, your project seems pretty neat; I've got it all up and running and have walked through your readme and aside from some hardware related problems that I've worked out, it seems to be functioning properly. I really appreciate you making this open source.

That being said, the whole thing is useless unless I send you my CSV file because you haven't published the calibration code along with the rest of your project. If I want to experiment with moving my cameras around (or worse, the cameras move on their own due to gravity or dart strikes) I have to send my CSV over and over again. Or if I was willing to contribute to make the calibration code better; that's simply not possible.

I was just a little disappointed yesterday when I was calibrating your OSS project (released under the GPL) that is ostensibly useless without some secret proprietary code. In fact, the version of the code I had checked out still had your note in it saying to run  `java -cp darts-1.0-jar-with-dependencies.jar darts.DartsCalibration`, so I looked for that and figured you just forgot to check it in.

But it's your project. I could try to reverse engineer what the calib code is trying to do I guess.

**Comment by vassdoki** [comment]
I see your point. I will change the readme file to show this fact clearly. It takes some time to provide the calibration as an online service, because I'm focusing on the scoreboard right now. Thanks for your comment.

**Comment by jamie-nxtgencare** [comment]
So you don't intend to offer the source code for calibration?

**Comment by vassdoki** [comment]
Right now I'm trying to figure out how to monetize the project. For that reason, I offer the calibration as a service, and not the source code.

**Comment by jamie-nxtgencare** [comment]
Understandable. Good luck.
