### ISSUE TITLE
Dartsee scoreboard error

### ISSUE THREAD

**Issue by vassdoki** [vassdoki/opencv-darts#3]
@patrickhener reported this:

> I invested some time into testing you scoreboard. I understand
> how GET calls work against the scoreboard one creates and I am able to
> "simulate" darts thrown this way. But no matter what game I choose or
> what settings I use after having "thrown" three darts the border
> switches to player number 2 but if I simulate a dart beeing trown again
> it switches back to player number 1 and counts that dart as a fourth
> dart thrown with player number 2. How can we work this out?

**Comment by vassdoki** [comment]
This is an incompatibility of this project and the online scoreboard. I will fix it.

The current online scoreboard has one more function to switch to the next
player. I'll have to implement that here also.

**Comment by patrickhener** [comment]
I appreciate this. Thank you!

**Comment by vassdoki** [comment]
This should fix the problem, but I cannot test it. Please reopen the issue if there is any problem.
