### ISSUE TITLE
Maven Build Throws several Warnings (but does build)

### ISSUE THREAD

**Issue by ibakejj** [vassdoki/opencv-darts#4]
I get the following errors when trying to compile the jar with Maven.

It does build, and creates the .jar, but I wonder if these build warnings may be related to other Issues.

Having said this, it will run on my Mac. RPI build does not work for the same reasons outlines in the 'No function after building' Issue posted by patrick

Maven Build Warnings:

[WARNING] Some problems were encountered while building the effective model for hu.imind.vassdoki:darts:jar:1.0
[WARNING] 'dependencies.dependency.version' for org.scala-lang.modules:scala-swing_2.10:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 71, column 22
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 78, column 21
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] Could not validate integrity of download from http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.10/maven-metadata.xml: Checksum validation failed, expected 5ff6d732e8299e4055aae79ecd2c55a780d8d67c but is 452d569b40b7cf3498176f3df095de592ca366a8
[WARNING] Checksum validation failed, expected 5ff6d732e8299e4055aae79ecd2c55a780d8d67c but is 452d569b40b7cf3498176f3df095de592ca366a8 from central for http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.10/maven-metadata.xml
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[WARNING]  Expected all dependencies to require Scala version: 2.10.3
[WARNING]  hu.imind.vassdoki:darts:1.0 requires scala version: 2.10.3
[WARNING]  org.scala-lang.modules:scala-swing_2.10:2.0.0-M2 requires scala version: 2.10.4
[WARNING] Multiple versions of scala libraries detected!
[WARNING] warning: there were 1 deprecation warning(s); re-run with -deprecation for details
[WARNING] warning: there were 7 feature warning(s); re-run with -feature for details
[WARNING] two warnings found

**Comment by vassdoki** [comment]
I have migrated to newer scala version.
The build did work for me.
